language: java
jdk:
  - openjdk12
sudo: false
script: sh scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 559383fc-b245-40a1-9924-0f9188074c5d
env:
  global:
    - CODECOV_TOKEN=:559383fc-b245-40a1-9924-0f9188074c5d